import { useEffect, useState } from 'react'
import './App.css'
const products=[{id:'farcie',name:'Farcie Burger',category:'Burgers',price:79,image:'classic',tag:'LE GÉNÉREUX',desc:'Steak farci mozzarella, cheddar, salade, tomate, pickles et sauce Burn’s.'},{id:'banger',name:'Smash Banger',category:'Burgers',price:65,image:'combo',tag:'BEST-SELLER',desc:'Steak smashé, tenders spicy, cheddar, oignons caramélisés et sauce Burn’s.'},{id:'bowl',name:'Burn’s Bowl',category:'Bowls & sides',price:57,image:'bowl',tag:'COMFORT FOOD',desc:'Tenders, frites maison épicées, cheddar fondant et oignons crispy.'},{id:'student',name:'Menu Smash Étudiant',category:'Menus',price:49,image:'combo',tag:'LE MIDI',desc:'Steak smashé, cheddar, salade et sauce maison. Avec frites maison épicées.'}]
const money=n=>`${n} DH`
function Icon({name}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{name==='bag'?<><path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></>:name==='user'?<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>:name==='star'?<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>:name==='clock'?<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>:<path d="M3 7h18M3 12h18M3 17h18"/>}</svg>}
const Brand=()=> <a className="brand" href="#home"><span className="brand-mark">B</span><span>BURN’S<small>US SMASH BURGER</small></span></a>
function App(){
const [page,setPage]=useState(location.hash.slice(1)||'home'),[cart,setCart]=useState({}),[category,setCategory]=useState('Tout le menu'),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false),[saved,setSaved]=useState(false),[ordered,setOrdered]=useState(false)
const [profile,setProfile]=useState(()=>{try{return JSON.parse(localStorage.getItem('burns-demo-profile'))||{name:'',email:'',phone:''}}catch{return {name:'',email:'',phone:''}}})
const count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((a,p)=>a+p.price*(cart[p.id]||0),0)
useEffect(()=>{const handle=()=>{setPage(location.hash.slice(1)||'home');setMobile(false);window.scrollTo(0,0)};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle)},[])
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)}},[toast])
const add=p=>{setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}));setOrdered(false);setToast(`${p.name} ajouté au panier`)}
useEffect(()=>{if(!document.modelContext?.registerTool)return;const abort=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_burns_menu',description:'Read the available Burn’s menu and prices in Moroccan dirhams.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>products},{signal:abort.signal})).catch(()=>{})}catch{}return()=>abort.abort()},[])
const cards=items=><div className="product-grid">{items.map(p=><article className="product-card" key={p.id}><div className="product-photo"><img src={`/images/${p.image}.png`} alt={p.name}/><span className="product-tag">{p.tag}</span><button className="add" aria-label={`Ajouter ${p.name}`} onClick={()=>add(p)}>+</button></div><div className="product-info"><h3>{p.name}</h3><strong>{money(p.price)}</strong><p>{p.desc}</p></div></article>)}</div>
return <><div className="announcement">SMASHÉ AVEC PASSION. DÉVORÉ SANS MODÉRATION. <span>100% BURN’S.</span></div><header><Brand/><nav className={mobile?'open':''} aria-label="Navigation principale">{[['home','Accueil'],['menu','Le menu'],['offers','Offres spéciales'],['fidelity','Fidélité']].map(([id,label])=><a className={page===id?'active':''} key={id} href={`#${id}`}>{label}</a>)}</nav><div className="header-actions"><a href="#profile" aria-label="Mon profil"><Icon name="user"/></a><a className="cart-button" aria-label={`Commander, ${count} articles`} href="#order"><Icon name="bag"/><span>Commander</span><b>{count}</b></a><button className="mobile-toggle" aria-label="Ouvrir la navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Icon/></button></div></header><main>
{page==='home'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> LE VRAI GOÛT DU SMASH.</div><h1>BIG SMASH.<br/><em>BIG LOVE.</em></h1><p>Une croûte dorée. Du cheddar qui fond.<br/>Des burgers qui ne font pas les choses à moitié.</p><div className="hero-buttons"><a className="button pink" href="#menu">Découvrir le menu <Icon name="bag"/></a><a className="text-link" href="#offers">Nos offres du moment</a></div><div className="hero-proof"><span><Icon name="star"/> Smashé à la commande</span><span><Icon name="clock"/> Préparé avec passion</span></div></div><div className="hero-visual"><img src="/images/combo.png" alt="Smash burger Burn’s avec cheddar, frites et tender croustillant"/><div className="round-stamp">SMASH IT.<br/><b>LOVE IT.</b><span>★ BURN’S ★</span></div><div className="photo-caption"><span>LE CRUSH DU MOMENT</span><b>Le goût. Sans compromis.</b></div></div></section><div className="marquee"><span>SMASHED TO PERFECTION</span><b>✳</b><span>FRESH. JUICY. CRISPY.</span><b>✳</b><span>ALL YOU NEED IS BURN’S</span><b>✳</b><span>SMASHED TO PERFECTION</span></div><section className="section"><div className="section-title"><div><span className="eyebrow">LES INCONTOURNABLES</span><h2>Ton prochain <em>coup de cœur.</em></h2></div><a className="outline-button" href="#menu">Voir tout le menu</a></div>{cards(products.slice(0,3))}</section><section className="loyalty-banner"><div><span className="eyebrow">LA FAMILLE BURN’S</span><h2>Plus de smash.<br/><em>Plus de privilèges.</em></h2><p>Ton prochain rendez-vous gourmand commence ici.</p><a className="button dark" href="#fidelity">Découvrir la fidélité <Icon name="star"/></a></div><div className="member-card"><span>BURN’S <Icon name="star"/></span><h3>GOOD FOOD.<br/>GREAT COMPANY.</h3><small>LE CLUB BURN’S · CARTE FIDÉLITÉ</small></div></section><section className="story section"><img src="/images/craft.png" alt="Préparation d’un burger Burn’s en cuisine"/><div><span className="eyebrow">DU GRILL À TON CŒUR</span><h2>Du caractère.<br/>Et beaucoup de <em>cheddar.</em></h2><p>Un steak smashé sur le grill, des oignons caramélisés, une sauce signature. Chez Burn’s, le bonheur se tient à deux mains.</p><a href="#menu" className="outline-button">Trouver mon burger</a></div></section></>}
{page==='menu'&&<section className="section page-content"><span className="eyebrow">FAIS PLACE À LA GOURMANDISE</span><h1>Le <em>menu.</em></h1><p>Smash burgers, bowls généreux et petits plaisirs.</p><div className="filters" aria-label="Catégories">{['Tout le menu','Burgers','Menus','Bowls & sides','Desserts'].map(c=><button aria-pressed={c===category} className={c===category?'selected':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>{category==='Desserts'?<div className="dessert-feature"><img src="/images/cookies.png" alt="Cookies chocolat et caramel Burn’s"/><div><span className="eyebrow">LA TOUCHE SUCRÉE</span><h2>Cookie love.</h2><p>Chocolat fondant, cœur caramel et beaucoup de gourmandise.</p><p>Prix et disponibilités à confirmer au restaurant.</p></div></div>:cards(products.filter(p=>category==='Tout le menu'||p.category===category))}<p className="fine-print">Prix repris de la carte fournie. Disponibilité et allergènes à confirmer auprès du restaurant.</p></section>}
{page==='offers'&&<section className="section page-content"><span className="eyebrow">PETIT PRIX. GRAND PLAISIR.</span><h1>Les offres <em>qui régalent.</em></h1><div className="offer-feature"><img src="/images/combo.png" alt="Menu smash étudiant avec frites"/><div><span className="pill">UNIQUEMENT LE MIDI</span><h2>La pause dej’<br/>a du <em>caractère.</em></h2><p>Le Menu Smash Étudiant : steak smashé, cheddar, salade, pomme paille, oignons caramélisés et sauce maison. Servi avec frites maison épicées.</p><div className="offer-price">49 <small>DH</small></div><button className="button pink" onClick={()=>add(products[3])}>Ajouter au panier <Icon name="bag"/></button><p className="fine-print">Offre issue de la carte fournie. Conditions et disponibilité à confirmer sur place.</p></div></div></section>}
{page==='fidelity'&&<section className="section page-content"><span className="eyebrow">BIENVENUE DANS LA FAMILLE</span><h1>Le club <em>Burn’s.</em></h1><div className="account-grid"><div className="member-card large"><span>BURN’S <Icon name="star"/></span><h3>{profile.name||'SMASH LOVER'}<br/>LE GOÛT NOUS RÉUNIT.</h3><small>CARTE FIDÉLITÉ · APERÇU</small></div><div className="panel"><h2>La fidélité a du bon.</h2><p>Retrouve ici ta future carte et tes récompenses Burn’s.</p><div className="stamps">{Array.from({length:5},(_,i)=><span key={i}><Icon name="star"/></span>)}</div><p className="notice">Le programme fidélité n’est pas encore actif. Les règles et récompenses seront annoncées par le restaurant.</p><a href="#profile" className="button pink">Personnaliser mon profil</a></div></div></section>}
{page==='profile'&&<section className="section page-content"><span className="eyebrow">TON COIN À TOI</span><h1>Mon <em>profil.</em></h1><div className="account-grid"><div><h2>Salut, {profile.name||'smash lover'}.</h2><p>Personnalise ton expérience Burn’s.</p><p className="notice">Profil de démonstration, enregistré uniquement dans ce navigateur. Aucun compte en ligne n’est créé.</p></div><form className="panel" onSubmit={e=>{e.preventDefault();try{localStorage.setItem('burns-demo-profile',JSON.stringify(profile));setSaved(true)}catch{setToast('Enregistrement indisponible dans ce navigateur.')}}}>{[['name','Prénom','text','Ton prénom'],['email','E-mail','email','toi@exemple.com'],['phone','Téléphone','tel','06 00 00 00 00']].map(([key,label,type,placeholder])=><label key={key}>{label}<input type={type} required={key!=='phone'} value={profile[key]} placeholder={placeholder} onChange={e=>{setSaved(false);setProfile({...profile,[key]:e.target.value})}}/></label>)}<button className="button pink" type="submit">Enregistrer mon profil</button>{saved&&<p role="status">✓ Profil enregistré sur cet appareil.</p>}</form></div></section>}
{page==='order'&&<section className="section page-content"><span className="eyebrow">LE BONHEUR EST DANS LE SAC</span><h1>Ma <em>commande.</em></h1>{ordered?<div className="panel empty"><Icon name="bag"/><h2>Ton récapitulatif est prêt.</h2><p>Ceci est une commande de démonstration. Rien n’a été envoyé au restaurant et aucun paiement n’a été effectué.</p><button className="button pink" onClick={()=>setOrdered(false)}>Revenir au panier</button></div>:count?<div className="order-grid"><div>{products.filter(p=>cart[p.id]).map(p=><div className="cart-row" key={p.id}><img src={`/images/${p.image}.png`} alt={p.name}/><div><h3>{p.name}</h3><p>{money(p.price)}</p></div><div className="quantity"><button aria-label={`Retirer un ${p.name}`} onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,c[p.id]-1)}))}>−</button><span>{cart[p.id]}</span><button aria-label={`Ajouter un ${p.name}`} onClick={()=>add(p)}>+</button></div><strong>{money(p.price*cart[p.id])}</strong></div>)}</div><div className="panel summary"><h2>Le récap’</h2><p><span>{count} article{count>1?'s':''}</span><b>{money(total)}</b></p><p><span>Retrait au restaurant</span><b>Gratuit</b></p><div className="total"><span>Total</span><b>{money(total)}</b></div><p className="notice">Mode démo : la commande en ligne et le paiement ne sont pas encore connectés.</p><button className="button pink" onClick={()=>setOrdered(true)}>Valider le panier démo</button><a className="text-link" href="#menu">Continuer mes achats</a></div></div>:<div className="panel empty"><Icon name="bag"/><h2>Un petit creux ?</h2><p>Ton panier attend son premier smash.</p><a className="button pink" href="#menu">Explorer le menu</a></div>}</section>}
{!['home','menu','offers','fidelity','profile','order'].includes(page)&&<section className="section page-content"><h1>Page introuvable.</h1><a href="#home" className="button pink">Retour à l’accueil</a></section>}
</main><footer><Brand/><p>Du smash. De l’amour. Du Burn’s.</p><div><a href="#menu">Le menu</a><a href="#fidelity">Le club</a><a href="#profile">Mon profil</a></div><small>© {new Date().getFullYear()} Burn’s. All you need is smash.</small></footer>{toast&&<div className="toast" role="status">✓ {toast}</div>}</>
}
export default App

